# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '20.x'
  displayName: 'Install Node.js'

- script: |
    npm install && npx playwright install --with-deps
  displayName: 'npm install' 

- script: 
    npm run tests
  displayName: 'run the playwright tests' # Run the "tests" script defined in package.json

- task: PublishTestResults@2
  inputs:
    testResultsFiles: '**/test-results/**/*.xml'  # Publish Playwright test results if generated in JUnit format.
    testRunTitle: 'Chromium Tests'
    


